# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya/RxSwift', '~> 11.0'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Kingfisher', '~> 4.8.0'

  target 'BaseProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
